### ISSUE TITLE
Crops can fail to grow once their timer ends.

### ISSUE THREAD

**Issue by Inframission** [CivClassic/RealisticBiomes#10]
Birch tree growth seems to fail randomly.
Attempting to update ungrown saplings with a stick fails to spawn tree and yields one of two messages
* [Birch sapling will grow now](https://i.imgur.com/HlwDPOy.png)
* [Birch Sapling is 0.00% grown](https://i.imgur.com/7k5htQA.png)

[Here's the result.](https://i.imgur.com/SIdUrbi.png)  after waiting 8 hours in a forest biome where growth time is 3 hours

**Comment by Maxopoly** [comment]
Strange. Likely there is an implementation fault in the update timers for crops, need to debug that. Could also be caused by low (<20) tps, not sure, need to make it tps independent if it is.

Random patches not growing anything were already reported for other crops as well, but we still haven't determined what exactly is different in those locations. Chunk borders maybe? Your screenshot makes it seem like the spots that didn't grow are chunk sized with a few exceptions in them.

**Comment by Inframission** [comment]
> Random patches not growing anything were already reported for other crops as well, but we still haven't determined what exactly is different in those locations.

Patches in other crops do appear to be [chunk related](https://streamable.com/ahsf70). Thinking the tree issue here is the same.

**Comment by Maxopoly** [comment]
These do have growth timers, so they were put into the database, but they never grew. Could you check whether keeping the chunk unloaded for 10 minutes and then loading it fixes those crops?

**Comment by Inframission** [comment]
Like the saplings, coming back to wheat after leaving it unloaded doesn't cause growth.
[Here's the result](https://i.imgur.com/L6ViyX2.png) after waiting 9 hours -  unplanted spots to the west are intentional

Edit: It seems the specific chunks where crops fail to grow changes over time.
![QtbV1KN](https://user-images.githubusercontent.com/58122276/84718998-a9000880-af69-11ea-9034-1f64e08ba5a5.png)

**Comment by Maxopoly** [comment]
Possibly fixed by https://github.com/CivClassic/RealisticBiomes/commit/0f4a3cb880c9eb6685c3add83a58896b61c93f93, please report back after restart

**Comment by squareblob** [comment]
0f4a3cb did not fix the issue. Crops still sometimes fail to grow

**Comment by Maxopoly** [comment]
Should be severely improved upon in https://github.com/CivClassic/RealisticBiomes/pull/25

**Comment by Inframission** [comment]
~~Testing myself, this issue seems resolved and I haven't seen feedback saying otherwise. Closing for now.~~

**Comment by Maxopoly** [comment]
Probably fixed by https://github.com/CivClassic/RealisticBiomes/commit/1c8b18d5b34f2be808c1a6503fd3550f633af5cc, but keeping the issue open until confirmed fixed

**Comment by Maxopoly** [comment]
Feedback on whether this was fixed by https://github.com/CivClassic/RealisticBiomes/commit/3a8fa6049d19889a0692f7a3780d81e2a24985b2 please

**Comment by Maxopoly** [comment]
Seemingly fixed
