### ISSUE TITLE
Non-plants will show growth rate

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/RealisticBiomes#4]
Crops not specified in the config will grow at vanilla rates. This leads to RB messages for stuff like Minecarts when hitting the ground with them.

**Comment by crimsonblod** [comment]
You can also right click people, and it will show this.

https://i.imgur.com/ixc31JR.png

**Comment by squareblob** [comment]
I am no longer able to replicate the original issue. It seems it may have been fixed [June 2019?](https://github.com/CivClassic/RealisticBiomes/blame/f17b55c580896e37f2ed1755686f9082c35a444e/src/main/java/com/untamedears/realisticbiomes/listener/PlayerListener.java#L91) (unless there is another cause + my testing setup is wrong). 

https://github.com/CivClassic/RealisticBiomes/issues/4#issuecomment-657309360 is still current behavior.

**Comment by Maxopoly** [comment]
Might be partially fixed, we want a general solution that does only plants though

**Comment by Maxopoly** [comment]
Fully fixed thanks to https://github.com/CivClassic/RealisticBiomes/pull/13
